import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import ColorState from "./context/colors/ColorState";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Paintify",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0"
        ></meta>
      </head>

      <body className={inter.className}>
        <div className="bg-gray-100 font-sans">
          <ColorState>
            <Navbar />
            {children}
          </ColorState>
        </div>
      </body>
    </html>
  );
}
